// Firebase mode: real quests generated by Cloud Functions from Gmail/Drive/Calendar.
// This adapter mirrors Firestore into the game store and derives celebration
// events from quest_events + asset diffs.

import { collection, onSnapshot, type Unsubscribe } from 'firebase/firestore'
import { db } from '../firebase/config'
import {
  getOrCreateIsland, getOrCreateUser, selfReportComplete,
  subscribeToIsland, subscribeToQuests, subscribeToQuestEvents,
} from '../firebase/firestore'
import type { DataAdapter } from '../state/gameStore'
import { useGameStore } from '../state/gameStore'
import type { CritterInstance, PlacedAsset, Quest } from '../state/types'
import { CRITTER_SPECIES } from '../state/types'

export async function createFirebaseAdapter(
  uid: string, email: string, displayName: string,
): Promise<DataAdapter> {
  const store = useGameStore
  const subs: Unsubscribe[] = []
  const knownQuests = new Map<string, Quest>()
  let prevLevel: number | null = null
  let latestAssets: PlacedAsset[] = []

  await getOrCreateUser(uid, email, displayName)
  await getOrCreateIsland(uid)

  subs.push(subscribeToIsland(uid, (island) => {
    store.getState().setIsland({
      level: island.level,
      xp: island.xp,
      xpToNextLevel: island.xpToNextLevel,
      season: island.season,
      streakCount: island.streakCount,
      unlockedAssetTypes: island.unlockedAssetTypes,
    })
    const critters: CritterInstance[] = (island.characters ?? []).map((c) => ({
      id: c.id,
      species: (CRITTER_SPECIES.has(c.asset) ? c.asset : 'cat') as CritterInstance['species'],
      name: c.name,
      rarity: c.rarity,
      home: { x: c.position.x, y: c.position.y },
      unlockDate: c.unlockDate,
    }))
    store.getState().setCritters(critters)

    if (prevLevel !== null && island.level > prevLevel) {
      store.getState().enqueueCelebration({
        kind: 'levelup',
        id: `cel-lvl-${island.level}-${Date.now()}`,
        newLevel: island.level,
        unlocked: island.unlockedAssetTypes,
      })
    }
    prevLevel = island.level
  }))

  subs.push(subscribeToQuests(uid, (quests) => {
    const mapped: Quest[] = quests.map((q) => ({
      id: q.id,
      source: q.source,
      title: q.title,
      difficulty: q.difficulty,
      xpReward: q.xpReward,
      rewardType: q.rewardType,
      status: q.status,
      createdAt: q.createdAt,
    }))
    for (const q of mapped) knownQuests.set(q.id, q)
    store.getState().setQuests(mapped)
  }))

  // Assets subcollection → store; critter-species assets are filtered out
  // (they render as critters, not props).
  subs.push(onSnapshot(collection(db, 'islands', uid, 'assets'), (snap) => {
    latestAssets = snap.docs
      .map((d) => {
        const data = d.data()
        return {
          id: d.id,
          type: data.type as string,
          gridX: data.gridX as number,
          gridY: data.gridY as number,
          plantedAt: data.plantedAt as number,
          growthStage: (data.growthStage as number) ?? 1,
        }
      })
      .filter((a) => !CRITTER_SPECIES.has(a.type))
    store.getState().setAssets(latestAssets)
  }))

  // Celebrations: a 'completed' quest event fires the sequence. We wait a beat
  // so the Cloud Function's asset write lands, then attach the newest asset.
  const sessionStart = Date.now()
  subs.push(subscribeToQuestEvents(uid, sessionStart, (events) => {
    for (const ev of events) {
      if (ev.type !== 'completed') continue
      const quest = knownQuests.get(ev.questId)
      if (!quest) continue
      knownQuests.delete(ev.questId)
      setTimeout(() => {
        const newest = latestAssets
          .filter((a) => a.plantedAt > Date.now() - 15_000)
          .sort((a, b) => b.plantedAt - a.plantedAt)[0]
        store.getState().enqueueCelebration({
          kind: 'quest',
          id: `cel-${ev.questId}`,
          quest: { ...quest, status: 'completed' },
          rewardAssetId: newest?.id ?? null,
          rewardCritterId: null,
        })
      }, 1800)
    }
  }))

  return {
    async completeQuest(questId) {
      await selfReportComplete(questId, uid)
    },
    async moveAsset() {
      // Server owns placement in firebase mode (arrange sync not implemented yet).
    },
    dispose() {
      for (const u of subs) u()
    },
  }
}
